buhalter/buhalter/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('money_calc/', include('money_calc.urls')),
]

buhalter/money_calc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('orders', views.orders, name='orders'),
    path('not_pay_orders', views.not_pay_orders, name='not_pay_orders'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),
    path('<int:pk>/update', views.OrderUpdateView.as_view(), name='order-update'),
    path('<int:pk>/delete', views.OrderDeleteView.as_view(), name='order-delete'),
    path('worker', views.worker, name='worker'),
    path('create-worker', views.create_worker, name='create-worker'),
    path('worker/<int:pk>/update', views.WorkerUpdateView.as_view(), name='worker-update'),
    path('worker/<int:pk>/delete', views.WorkerDeleteView.as_view(), name='worker-delete'),
    path('worker/<int:worker_id>', views.worker_orders, name='worker-orders'),
    path('agent', views.agent, name='agent'),
    path('create-agent', views.create_agent, name='create-agent'),
    path('agent/<int:pk>/update', views.AgentUpdateView.as_view(), name='agent-update'),
    path('agent/<int:pk>/delete', views.AgentDeleteView.as_view(), name='agent-delete'),
    path('agent/<int:agent_id>', views.agent_orders, name='agent-detail'),
    path('expenses', views.expenses, name='expenses'),
    path('expense/<int:pk>', views.ExpensesDetailView.as_view(), name='expenses-expense'),
    path('create-expense', views.create_expense, name='create-expense'),
    path('expense/<int:pk>/update', views.ExpenseUpdateView.as_view(), name='expense-update'),
    path('expense/<int:pk>/delete', views.ExpenseDeleteView.as_view(), name='expense-delete'),
    path('tasks', views.tasks, name='tasks'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='tasks-task'),
    path('create-task', views.create_task, name='create-task'),
    path('task/<int:pk>/update', views.TaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete', views.TaskDeleteView.as_view(), name='task-delete'),
]

buhalter/money_calc/models.py
from django.db import models
from django.utils import timezone


class Agent(models.Model):
    id = models.AutoField(primary_key=True)
    agent_name = models.CharField(max_length=100, verbose_name='Имя заказчика')
    agent_phone = models.CharField(max_length=11, verbose_name='Телефон заказчика', unique=True)

    class Meta:
        verbose_name = 'Заказчик'
        verbose_name_plural = 'Заказчики'

    def __str__(self):
        return str(self.agent_name)


class Worker(models.Model):
    id = models.AutoField(primary_key=True)
    worker_name = models.CharField(max_length=100, verbose_name='Имя работника')
    worker_phone = models.CharField(max_length=11, verbose_name='Телефон работника')
    car = models.CharField(max_length=100, verbose_name='Машина и гос.номер', unique=True)

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

    def __str__(self):
        return str(self.worker_name)


class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    created_data = models.DateTimeField(auto_now_add=True)
    publish_data = models.DateField(default=timezone.now, verbose_name='Дата выполнения заказа')
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, verbose_name='Имя работника')
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, verbose_name='Имя заказчика')
    sum = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Сумма заказа', default=0)
    METHOD = [
        ('cash', 'Нал'),
        ('card', 'Безналл'),
        ('law', 'с НДС'),
    ]

    payment_method = models.CharField(max_length=100, choices=METHOD, verbose_name='Метод оплаты:')
    comment = models.TextField(max_length=350, verbose_name='Комментарий:')

    STATUS = [
        ('yes', 'Оплачено'),
        ('no', 'Ждет оплаты'),
    ]

    payment_status = models.CharField(max_length=50, choices=STATUS, verbose_name='Статус платежа:')

    def get_absolute_url(self):
        return f'/money_calc/{self.order_id}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ №{self.order_id} - {self.publish_data} - {self.worker} - {self.agent} - {self.sum}'


class Expenses(models.Model):
    id = models.AutoField(primary_key=True)
    expense = models.CharField(max_length=250, verbose_name='Наименование траты')
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Сумма трат')
    data_expense = models.DateField(auto_now_add=True, verbose_name='Когда потратил ?')

    class Meta:
        verbose_name = 'Трата'
        verbose_name_plural = 'Расходы'

    def __str__(self):
        return f'{self.expense} - {self.cost}₽ {self.data_expense}'


class Tasks(models.Model):
    id = models.AutoField(primary_key=True)
    created_data = models.DateTimeField(auto_now_add=True)
    publish_data = models.DateField(default=timezone.now, verbose_name='Дэдлайн')
    comment = models.TextField(max_length=350, verbose_name='Комментарий:')

    TYPE = [
        ('1', 'Не важно'),
        ('2', 'Средне'),
        ('3', 'Важно'),
    ]

    task_type = models.CharField(max_length=100, choices=TYPE, verbose_name='Степень важности:')

    STATUS = [
        ('1', 'Не начал'),
        ('2', 'В процессе'),
        ('3', 'Выполнил'),
    ]

    task_status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус выполнения:')

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'{self.comment} - {self.task_status}₽ {self.task_type}'

buhalter/money_calc/views.py
from datetime import date

from babel.dates import format_date
from django.db.models import Avg, Func
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import DetailView, UpdateView, DeleteView

from .forms import OrderForm, WorkerForm, AgentForm, ExpensesForm, TaskForm
from .models import Order, Worker, Agent, Expenses, Tasks


def orders(request):
    today = timezone.now().date()
    latest_order_list = Order.objects.order_by('-publish_data').filter(publish_data__lte=today)
    future_orders = Order.objects.filter(publish_data__gt=today)

    context = {
        'latest_order_list': latest_order_list,
        'future_orders': future_orders,
    }
    return render(request, 'money_calc/orders.html', context)


def not_pay_orders(request):
    latest_order_list = Order.objects.filter(payment_status='no')
    context = {
        'latest_order_list': latest_order_list,
    }
    return render(request, 'money_calc/not_pay_orders.html', context)


def worker(request):
    latest_worker_list = Worker.objects.order_by('-worker_name')
    context = {'latest_worker_list': latest_worker_list}
    return render(request, 'money_calc/worker.html', context)


def agent(request):
    latest_agent_list = Agent.objects.order_by('-agent_name')
    context = {'latest_agent_list': latest_agent_list}
    return render(request, 'money_calc/agent.html', context)


def expenses(request):
    latest_expenses_list = Expenses.objects.order_by('-id')
    context = {'latest_expenses_list': latest_expenses_list}
    return render(request, 'money_calc/expenses.html', context)


def tasks(request):
    latest_task_list = Tasks.objects.order_by('-id')
    context = {'latest_task_list': latest_task_list}
    return render(request, 'money_calc/tasks.html', context)


class OrderDetailView(DetailView):
    model = Order
    template_name = 'money_calc/details_view.html'
    context_object_name = 'order'


class OrderUpdateView(UpdateView):
    model = Order
    template_name = 'money_calc/create_order.html'

    form_class = OrderForm


class OrderDeleteView(DeleteView):
    model = Order
    success_url = ''
    template_name = 'money_calc/order-delete.html'


class WorkerUpdateView(UpdateView):
    model = Worker
    template_name = 'money_calc/update_worker.html'
    success_url = '/worker'
    form_class = WorkerForm


class WorkerDeleteView(DeleteView):
    model = Worker
    success_url = '/worker'
    template_name = 'money_calc/worker-delete.html'


class AgentUpdateView(UpdateView):
    model = Agent
    template_name = 'money_calc/update_agent.html'
    success_url = '/agent'
    form_class = AgentForm


class AgentDeleteView(DeleteView):
    model = Agent
    success_url = '/agent'
    template_name = 'money_calc/agent-delete.html'


def create(request):
    error = ''

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('orders')
        else:
            error = 'Form is not valid'

    form = OrderForm()

    data = {
        'form': form,
        'error': error,
    }

    return render(request, 'money_calc/create_order.html', data)


def create_worker(request):
    error = ''

    if request.method == 'POST':
        form = WorkerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('worker')
        else:
            error = 'Form is not valid'

    form = WorkerForm()

    data = {
        'form': form,
        'error': error,
    }

    return render(request, 'money_calc/create_worker.html', data)


def create_agent(request):
    error = ''

    if request.method == 'POST':
        form = AgentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agent')
        else:
            error = 'Form is not valid'

    form = AgentForm()

    data = {
        'form': form,
        'error': error,
    }

    return render(request, 'money_calc/create_agent.html', data)


def worker_orders(request, worker_id):
    worker = Worker.objects.get(id=worker_id)
    orders = Order.objects.filter(worker=worker)
    cash_orders = Order.objects.filter(worker=worker, payment_method='cash')
    card_orders = Order.objects.filter(worker=worker, payment_method='card')
    law_orders = Order.objects.filter(worker=worker, payment_method='law')
    total_sum = 0
    for order in orders:
        total_sum += order.sum

    cash = 0
    for order in cash_orders:
        cash += order.sum

    card = 0
    for order in card_orders:
        card += order.sum

    law = 0
    for order in law_orders:
        law += order.sum

    count_order = orders.count()

    if count_order > 0:
        avg_order_sum = total_sum / count_order
    else:
        avg_order_sum = 0

    context = {
        'worker': worker,
        'orders': orders,
        'total_sum': total_sum,
        'avg_order_sum': avg_order_sum,
        'cash': cash,
        'card': card,
        'law': law,
    }

    return render(request, 'money_calc/worker_orders.html', context)


def agent_orders(request, agent_id):
    agent = Agent.objects.get(id=agent_id)
    orders = Order.objects.filter(agent=agent)
    cash_orders = Order.objects.filter(agent=agent, payment_method='cash')
    card_orders = Order.objects.filter(agent=agent, payment_method='card')
    law_orders = Order.objects.filter(agent=agent, payment_method='law')
    total_sum = 0

    for order in orders:
        total_sum += order.sum

    cash = 0
    for order in cash_orders:
        cash += order.sum

    card = 0
    for order in card_orders:
        card += order.sum

    law = 0
    for order in law_orders:
        law += order.sum

    count_order = orders.count()

    if count_order > 0:
        avg_order_sum = total_sum / count_order
    else:
        avg_order_sum = 0

    context = {
        'agent': agent,
        'orders': orders,
        'total_sum': total_sum,
        'avg_order_sum': avg_order_sum,
        'cash': cash,
        'card': card,
        'law': law,
    }

    return render(request, 'money_calc/agent_view.html', context)


class Round(Func):
    function = 'ROUND'
    template = '%(function)s(%(expressions)s, 0)'


def index(request):
    expenses = Expenses.objects.all()
    orders = Order.objects.all()

    orders_pay = Order.objects.filter(payment_status='yes')
    orders_pay_cash = Order.objects.filter(payment_status='yes', payment_method='cash')
    orders_pay_card = Order.objects.filter(payment_status='yes', payment_method='card')
    orders_pay_law = Order.objects.filter(payment_status='yes', payment_method='law')
    orders_pay_cash_count = orders_pay_cash.count()
    orders_pay_card_count = orders_pay_card.count()
    orders_pay_law_count = orders_pay_law.count()

    orders_not_pay = Order.objects.filter(payment_status='no')
    orders_not_pay_cash = Order.objects.filter(payment_status='no', payment_method='cash')
    orders_not_pay_card = Order.objects.filter(payment_status='no', payment_method='card')
    orders_not_pay_law = Order.objects.filter(payment_status='no', payment_method='law')
    orders_not_pay_cash_count = orders_not_pay_cash.count()
    orders_not_pay_card_count = orders_not_pay_card.count()
    orders_not_pay_law_count = orders_not_pay_law.count()

    count_order = orders.count()
    orders_pay_count = orders_pay.count()
    orders_not_pay_count = orders_not_pay.count()

    expense_sum = 0
    for expense in expenses:
        expense_sum += expense.cost

    total_sum = 0
    for order in orders:
        total_sum += order.sum

    avg_order_sum = total_sum / count_order

    pay_sum = 0
    for pay in orders_pay:
        pay_sum += pay.sum

    not_pay_sum = 0
    for pay in orders_not_pay:
        not_pay_sum += pay.sum

    latest_expense_list = Expenses.objects.order_by('-id')[:5]

    order_analytics = Order.objects.values('publish_data__week_day').annotate(total=Round(Avg('sum')))

    analytics = [0] * 7
    for analytics_data in order_analytics:
        day_of_week = analytics_data['publish_data__week_day']
        total_amount = analytics_data['total']
        analytics[day_of_week - 1] = total_amount

    locale = "ru_RU"
    day_names = [format_date(date(2022, 1, i + 1), format="eee", locale=locale) for i in range(7)]

    context = {
        'expenses': expenses,
        'orders': orders,
        'expense_sum': expense_sum,
        'total_sum': total_sum,
        'count_order': count_order,
        'orders_pay': orders_pay,
        'orders_not_pay': orders_not_pay,
        'pay_sum': pay_sum,
        'not_pay_sum': not_pay_sum,
        'orders_pay_count': orders_pay_count,
        'orders_pay_cash': orders_pay_cash,
        'orders_pay_card': orders_pay_card,
        'orders_pay_law': orders_pay_law,
        'orders_pay_cash_count': orders_pay_cash_count,
        'orders_pay_card_count': orders_pay_card_count,
        'orders_pay_law_count': orders_pay_law_count,
        'orders_not_pay_count': orders_not_pay_count,
        'orders_not_pay_cash': orders_not_pay_cash,
        'orders_not_pay_card': orders_not_pay_card,
        'orders_not_pay_law': orders_not_pay_law,
        'orders_not_pay_cash_count': orders_not_pay_cash_count,
        'orders_not_pay_card_count': orders_not_pay_card_count,
        'orders_not_pay_law_count': orders_not_pay_law_count,
        'latest_expense_list': latest_expense_list,
        'analytics': analytics,
        'day_names': day_names,
        'avg_order_sum': avg_order_sum,
    }

    return render(request, 'money_calc/index.html', context)


class ExpensesDetailView(DetailView):
    model = Expenses
    template_name = 'money_calc/expenses-expense.html'
    context_object_name = 'expense'


def create_expense(request):
    error = ''

    if request.method == 'POST':
        form = ExpensesForm(request.POST)
        if form.is_valid():
            form.save()

buhalter/money_calc/templates/money_calc/agent-delete.html
{% extends 'money_calc/layout.html' %}

{% block title %}Удаление заказчика{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h3>Удаление заказчика: {{ agent.id }}</h3>
            <form method="post">
                {% csrf_token %}
                <p>{{ agent.agent_name }}</p>
                <p>{{ agent.agent_phone }}</p>
                <span>{{ error }}</span>
                <p>Вы точно хотите удалить этого заказчика ?</p>
                <button class="btn btn-success" type="submit">Удалить заказчика</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/agent.html
{% extends 'money_calc/layout.html' %}

{% block title %}Заказчики{% endblock %}

{% block content %}

{% if latest_agent_list %}

    <div class="container">
        <div class="row">

            {% for agent in latest_agent_list %}

            <div class="col-md-4 block">

                <div class="field-block">{{ agent.agent_name }}</div>
                <div class="field-block">{{ agent.agent_phone }}</div>
                <a href="{% url 'agent-detail' agent.id %}" class="text-block-btn">Посмотреть заказчика {{ worker.id }}</a>

            </div>

            {% endfor %}

        </div>
    </div>

{% else %}
    <p>No agents are available.</p>
{% endif %}

{% endblock %}

buhalter/money_calc/templates/money_calc/create_expense.html
{% extends 'money_calc/layout.html' %}

{% block title %}Добавление траты{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h1>Форма для добавления траты</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.expense }}
                {{ form.cost }}<br>
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Добавить трату</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/create_worker.html
{% extends 'money_calc/layout.html' %}

{% block title %}Добавление работника{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h1>Форма для добавления работника</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.worker_name }}
                {{ form.worker_phone }}
                {{ form.car }}<br>
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Добавить работника</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

buhalter/money_calc/templates/money_calc/expense-delete.html
{% extends 'money_calc/layout.html' %}

{% block title %}Удаление траты{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h3>Удаление траты: {{ expenses.expense }}</h3>
            <form method="post">
                {% csrf_token %}
                <p>{{ expenses.expense }}</p>
                <p>{{ expenses.cost }}</p>
                <p>{{ expenses.data_expense }}</p>
                <span>{{ error }}</span>
                <p>Вы точно хотите удалить эту трату ?</p>
                <button class="btn btn-success" type="submit">Удалить трату</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/expenses-expense.html
{% extends 'money_calc/layout.html' %}

{% block title %}Трата{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <p>{{ expense.expense }}</p>
            <p>{{ expense.cost }}</p>
            <p>{{ expense.data_expense }}</p>

            <a href="{% url 'expense-delete' expense.id %}" class="btn btn-danger">Удалить трату</a>
            <a href="{% url 'expense-update' expense.id %}" class="btn btn-info">Обновить трату</a>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/expenses.html
{% extends 'money_calc/layout.html' %}

{% block title %}Расходы{% endblock %}

{% block content %}

{% if latest_expenses_list %}

<div class="container">
    <div class="row">

        {% for expense in latest_expenses_list %}

        <div class="col-md-12 order">

            <div class="col-md-3 field">{{ expense.expense }}</div>
            <div class="col-md-2 field">{{ expense.cost }}₽</div>
            <div class="col-md-2 field">{{ expense.data_expense }}</div>
            <a href="{% url 'expenses-expense' expense.id %}"><div class="col-md-2 text-btn">Посмотреть трату {{ expense.id }}</div></a>

        </div>

    {% endfor %}

{% else %}
    <p>No expenses are available.</p>
{% endif %}

    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/index.html
{% extends 'money_calc/layout.html' %}
{% load custom_filters %}

{% block title %}Заказы{% endblock %}

{% block content %}

<div class="container">
    <div class="row">

        <div class="col-md-4 index-item">
            <div class="analys">
                <h2 class="column-title">Аналитика</h2>
                <p class="punkt">Количество заказов: {{ count_order }}</p>
                <p class="punkt">Средний чек: {{ avg_order_sum|floatformat:0 }}₽</p>
                <p class="sub-punkt">Из них оплачено: {{ orders_pay_count }} шт.</p>
                <p class="pod-punkt">- Нал: {{ orders_pay_cash_count }} шт.</p>
                <p class="pod-punkt">- Безнал: {{ orders_pay_card_count }} шт.</p>
                <p class="pod-punkt">- с НДС: {{ orders_pay_law_count }} шт.</p>
                <p class="sub-punkt">Из них не оплачено: {{ orders_not_pay_count }} шт.</p>
                <p class="pod-punkt">- Нал: {{ orders_not_pay_cash_count }} шт.</p>
                <p class="pod-punkt">- Безнал: {{ orders_not_pay_card_count }} шт.</p>
                <p class="pod-punkt">- с НДС: {{ orders_not_pay_law_count }} шт.</p>

                <div class="anal-avg">

                    {% for day_name, analytics_value in day_names|slice:"1:"|zip_lists:analytics %}

                    <div class="anal-day">
                        <div class="day">{{ day_name }}</div>
                        <div class="day-avg">{{ analytics_value }}₽</div>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>

        <div class="col-md-4 index-item">
            <div class="profit">
                <h2 class="column-title">Доходы</h2>
                <p class="punkt">Сумма оплаченных заказов: {{ pay_sum }}₽</p>
                <p class="punkt">Сумма не оплаченных заказов: {{ not_pay_sum }}₽</p>
                <a href="{% url 'not_pay_orders' %}"><div class="text-index-btn">Посмотреть неоплаченные заказы</div></a>
            </div>
        </div>

        <div class="col-md-4 index-item">
            <div class="expenses">
                <a href="{% url 'expenses' %}"><h2 class="column-title exp">Расходы {{ expense_sum }}₽</h2></a>
                {% for expense in latest_expense_list %}
                    <p class="punkt">{{ expense }}</p>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/not_pay_orders.html
{% extends 'money_calc/layout.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}

{% if latest_order_list %}
    <div class="container">
        <div class="row">

            {% for order in latest_order_list %}

            <div class="col-md-12 order">

                <div class="col-md-2 field">{{ order.publish_data }}</div>
                <div class="col-md-2 field">{{ order.worker }}</div>
                <div class="col-md-2 field">{{ order.agent }}</div>
                <div class="col-md-2 field">{{ order.sum }}</div>
                <div class="col-md-1 field">{{ order.get_payment_method_display }}</div>
                <div class="col-md-2 field">{{ order.get_payment_status_display }}</div>
                <div class="col-md-8 comment">{{ order.comment|truncatechars:40 }}</div>
                <a href="{% url 'order-detail' order.order_id %}"><div class="col-md-3 text-btn">Посмотреть заказ #{{ order.order_id }}</div></a>

            </div>

            {% endfor %}

            {% else %}
                <p>No orders are available.</p>
            {% endif %}

        </div>
    </div>

{% endblock %}

buhalter/money_calc/templates/money_calc/task-delete.html
{% extends 'money_calc/layout.html' %}

{% block title %}Удаление задачи{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <form method="post">
                {% csrf_token %}
                <p>{{ tasks.comment }}</p>
                <p>{{ tasks.publish_data }}</p>
                <p>{{ tasks.get_task_type_display }}</p>
                <p>{{ tasks.get_task_status_display }}</p>
                <span>{{ error }}</span>
                <p>Вы точно хотите удалить эту задачу ?</p>
                <button class="btn btn-success" type="submit">Удалить задачу</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/tasks.html
{% extends 'money_calc/layout.html' %}

{% block title %}Задачи{% endblock %}

{% block content %}

{% if latest_task_list %}

<div class="container">
    <div class="row">

        {% for task in latest_task_list %}

        <div class="col-md-12 order">

            <div class="col-md-12 field">{{ task.comment }}</div>
            <div class="col-md-2 field">{{ task.get_task_type_display }}</div>
            <div class="col-md-2 field">{{ task.get_task_status_display }}</div>
            <div class="col-md-2 field">{{ task.publish_data }}</div>
            <a href="{% url 'tasks-task' task.id %}"><div class="col-md-2 text-btn">Посмотреть задачу {{ task.id }}</div></a>

        </div>

    {% endfor %}

{% else %}
    <p>No tasks are available.</p>
{% endif %}

    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/update_task.html
{% extends 'money_calc/layout.html' %}

{% block title %}Обновление задачи{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h1>Форма для обновления траты</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.comment }}
                {{ form.publish_data }}
                {{ form.task_type }}
                {{ form.task_status }}
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Обновить задачу</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buhalter/money_calc/templates/money_calc/worker-delete.html
{% extends 'money_calc/layout.html' %}

{% block title %}Удаление работника{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 main-info">
            <h3>Удаление работника: {{ worker.worker_name }}</h3>
            <form method="post">
                {% csrf_token %}
                <p>{{ worker.worker_name }}</p>
                <p>{{ worker.worker_phone }}</p>
                <p>{{ worker.car }}</p>
                <span>{{ error }}</span>
                <p>Вы точно хотите удалить этого работника ?</p>
                <button class="btn btn-success" type="submit">Удалить работника</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}